package analise.sintatica.producoes;

public enum ProducoesEnum {
	program,
	module,
	block,
	definitionPart,
	definition,
	constantDef,
	variableDef,
	type,
	typeSymbol,
	tupletype,
	arraytype,
	rangetype,
	variableList,
	typedef,
	procedureDecl,
	procedureDef,
	paramPart,
	paramDef,
	statementPart,
	statement,
	emptyStatement,
	readStatement,
	variableAccessList,
	writeStatement,
	writeItem,
	expressionList,
	assignStatement,
	ifStatement,
	guardedCommandList,
	guardedCommand,
	doStatement,
	forStatement,
	returnStatement,
	callStatement,
	argumentList,
	expression,
	booleanOperator,
	relationalExpression,
	relationalOperator,
	simpleExpression,
	term,
	factor,
	addingOperator,
	multiplyOperator,
	constantName,
	variableAccess,
	variableMore,
	nextitem,
	indexorcomp,
	constant,
	booleanConstant
	
	
}
